# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = ["github.com/mailru/easyjson"]

[[constraint]]
  name = "github.com/gin-gonic/gin"
  branch = "master"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.4"

[[constraint]]
  name = "github.com/evalphobia/logrus_sentry"
  version = "~0.4.3"

[[constraint]]
  name = "github.com/tinylib/msgp"
  branch = "master"

[[constraint]]
  name = "github.com/DataDog/dd-trace-go"
  version = "~0.6.1"

[[constraint]]
  name = "github.com/gin-contrib/gzip"
  branch = "master"

[[constraint]]
  name = "github.com/mongodb/mongo-go-driver"
  version = "=0.0.6"

[[constraint]]
  branch = "master"
  name = "github.com/mailru/easyjson"

[[constraint]]
  name = "github.com/pariz/gountries"
  version = "0.1.3"
